// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...

await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
);
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9uR1gqSp_xM7rpq0mEsB3kadtuZyExb0',
    appId: '1:194485468546:web:81a6d931a853f74e63239b',
    messagingSenderId: '194485468546',
    projectId: 'embeddedauc2',
    authDomain: 'embeddedauc2.firebaseapp.com',
    storageBucket: 'embeddedauc2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbVaWDqYK5Y4DPX55k7HSskSBlLtoZMyg',
    appId: '1:194485468546:android:4a19bf3d1fc80dda63239b',
    messagingSenderId: '194485468546',
    projectId: 'embeddedauc2',
    storageBucket: 'embeddedauc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPS93NOjDJD6XbZtCZ0fGnE23YGJKI8Kc',
    appId: '1:194485468546:ios:902e439673be1da963239b',
    messagingSenderId: '194485468546',
    projectId: 'embeddedauc2',
    storageBucket: 'embeddedauc2.appspot.com',
    iosBundleId: 'com.example.boidsgame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPS93NOjDJD6XbZtCZ0fGnE23YGJKI8Kc',
    appId: '1:194485468546:ios:699f42fb8b5aa02763239b',
    messagingSenderId: '194485468546',
    projectId: 'embeddedauc2',
    storageBucket: 'embeddedauc2.appspot.com',
    iosBundleId: 'com.example.boidsgame.RunnerTests',
  );
}
